config/routes.rb
Trellito::Application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit] do
      resources :lists, only: [:index, :show, :create, :update, :destroy]
    end
    resources :lists, only: [:show, :update, :destroy] do
      resources :cards, only: [:create, :index, :destroy]
    end
    resources :cards, only: [:show, :update, :destroy] do
      resources :todo_items, only: [:create, :index]
    end
    resources :todo_items, only: [:show, :update, :destroy]
    resources :card_assignments, only: :destroy
    resources :users, only: [:index]
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
end

app/views/layouts/_errors.html.erb
<% flash[:errors] && flash[:errors].each do |error| %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" 
      class="close" 
      data-dismiss="alert" 
      aria-hidden="true">&times;</button>
    <strong>Error:</strong>
    <%= error %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Trellito</a>
    </div>
    <ul class="nav navbar-right">
      <li>
        <% if logged_in? %>
          <%= button_to "Log out", session_url, {
            method: :delete,
            class: "btn btn-warning"
          } %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trellito</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>